version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/app/frontend"
    schedule:
      interval: "weekly"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/app/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
